### ISSUE TITLE
语言模型

### ISSUE THREAD

**Issue by Lebron-Kun** [Pelhans/ZASR_tensorflow#2]
请问，目前的RNN-CTC是可以实现端到端的语音识别的，可以直接输出汉字，那这个模型里面有语言模型吗？如果没有是不是外加一个语言模型效果会不会有提升？如果可以，那么需要怎么外加语言模型？

**Comment by Pelhans** [comment]
目前这个项目带语言模型解码。该部分由 utils/decoder/model.py 下的 decode_batch_beam_search()函数完成 。该函数接收一个2维的概率矩阵, 通过结合神经网络的输出概率和语言模型的评分来对输出进行解码。发自我的iPhone------------------ 原始邮件 ------------------发件人: Lebron-Kun  <notifications@github.com>发送时间: 2018年10月18日 16:57收件人: Pelhans/ZASR_tensorflow <ZASR_tensorflow@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[Pelhans/ZASR_tensorflow] 语言模型 (#2)请问，目前的RNN-CTC是可以实现端到端的语音识别的，可以直接输出汉字，那这个模型里面有语言模型吗？如果没有是不是外加一个语言模型效果会不会有提升？如果可以，那么需要怎么外加语言模型？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Pelhans/ZASR_tensorflow","title":"Pelhans/ZASR_tensorflow","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Pelhans/ZASR_tensorflow"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"语言模型 (#2)"}],"action":{"name":"View Issue","url":"https://github.com/Pelhans/ZASR_tensorflow/issues/2"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Pelhans/ZASR_tensorflow/issues/2",
"url": "https://github.com/Pelhans/ZASR_tensorflow/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "语言模型 (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Lebron-Kun**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Lebron-Kun",
"facts": [
{
"name": "Repository: ",
"value": "Pelhans/ZASR_tensorflow"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Pelhans/ZASR_tensorflow\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Pelhans/ZASR_tensorflow\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Pelhans/ZASR_tensorflow/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 397664680\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Lebron-Kun** [comment]
> 目前这个项目带语言模型解码。该部分由 utils/decoder/model.py 下的 decode_batch_beam_search()函数完成 。该函数接收一个2维的概率矩阵, 通过结合神经网络的输出概率和语言模型的评分来对输出进行解码。发自我的iPhone------------------ 原始邮件 ------------------发件人: Lebron-Kun <notifications@github.com>发送时间: 2018年10月18日 16:57收件人: Pelhans/ZASR_tensorflow <ZASR_tensorflow@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[Pelhans/ZASR_tensorflow] 语言模型 (#2)请问，目前的RNN-CTC是可以实现端到端的语音识别的，可以直接输出汉字，那这个模型里面有语言模型吗？如果没有是不是外加一个语言模型效果会不会有提升？如果可以，那么需要怎么外加语言模型？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Pelhans/ZASR_tensorflow","title":"Pelhans/ZASR_tensorflow","subtitle":"GitHub repository","main_image_url":"[https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://assets-cdn.github.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://assets-cdn.github.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/Pelhans/ZASR_tensorflow"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"语言模型](https://github.com/Pelhans/ZASR_tensorflow%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22DESCRIPTION%22,%22message%22:%22%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B) (#2)"}],"action":{"name":"View Issue","url":"#2"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#2", "url": "#2", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "语言模型 (#2)", "sections": [ { "text": "", "activityTitle": "**Lebron-Kun**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@Lebron-Kun", "facts": [ { "name": "Repository: ", "value": "Pelhans/ZASR_tensorflow" }, { "name": "Issue #: ", "value": 2 } ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Pelhans/ZASR_tensorflow\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Pelhans/ZASR_tensorflow\",\n\"issueId\": 2\n}" }, { "targets": [ { "os": "default", "uri": "#2" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 397664680\n}" } ], "themeColor": "26292E" } ]



> 目前这个项目带语言模型解码。该部分由 utils/decoder/model.py 下的 decode_batch_beam_search()函数完成 。该函数接收一个2维的概率矩阵, 通过结合神经网络的输出概率和语言模型的评分来对输出进行解码。发自我的iPhone------------------ 原始邮件 ------------------发件人: Lebron-Kun <notifications@github.com>发送时间: 2018年10月18日 16:57收件人: Pelhans/ZASR_tensorflow <ZASR_tensorflow@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[Pelhans/ZASR_tensorflow] 语言模型 (#2)请问，目前的RNN-CTC是可以实现端到端的语音识别的，可以直接输出汉字，那这个模型里面有语言模型吗？如果没有是不是外加一个语言模型效果会不会有提升？如果可以，那么需要怎么外加语言模型？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread. {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Pelhans/ZASR_tensorflow","title":"Pelhans/ZASR_tensorflow","subtitle":"GitHub repository","main_image_url":"[https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open](https://assets-cdn.github.com/images/email/message_cards/header.png%22,%22avatar_image_url%22:%22https://assets-cdn.github.com/images/email/message_cards/avatar.png%22,%22action%22:%7B%22name%22:%22Open) in GitHub","url":"[https://github.com/Pelhans/ZASR_tensorflow"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"语言模型](https://github.com/Pelhans/ZASR_tensorflow%22%7D%7D,%22updates%22:%7B%22snippets%22:%5B%7B%22icon%22:%22DESCRIPTION%22,%22message%22:%22%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B) (#2)"}],"action":{"name":"View Issue","url":"#2"}}} [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#2", "url": "#2", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "语言模型 (#2)", "sections": [ { "text": "", "activityTitle": "**Lebron-Kun**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@Lebron-Kun", "facts": [ { "name": "Repository: ", "value": "Pelhans/ZASR_tensorflow" }, { "name": "Issue #: ", "value": 2 } ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Pelhans/ZASR_tensorflow\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Pelhans/ZASR_tensorflow\",\n\"issueId\": 2\n}" }, { "targets": [ { "os": "default", "uri": "#2" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 397664680\n}" } ], "themeColor": "26292E" } ]

嗯，有点不懂就是我看您的代码里面可以选择使用不适用语言模型，如果不使用语言模型那么模型输出是什么？选择使用语言模型后模型的输出又是什么？语言模型是在什么地方用，CTC的输出是什么？

**Comment by Pelhans** [comment]
CTC输出是文字对应的数字编码，可以直接映射到文字。不使用语言模型也可以直接输出文字，语言模型只是对网络输出的概率结合语言模型的得分再综合得到一个输出。
